Repository sassoftware/viya4-iac-aws, pull requests merged in 2021-05, with the labels that each got.

#58 Added in SAS Viya 4 reference
  README.md
Labels: documentation

#61 Added prefix validation check and doc updates
  docs/CONFIG-VARS.md
  variables.tf
Labels: bug, documentation, enhancement

#52 Custom VPC module to support BYO
  docs/CONFIG-VARS.md
  docs/user/BYOnetwork.md
  examples/sample-input-byo.tfvars
  main.tf
  modules/aws_vm/main.tf
  modules/aws_vpc/main.tf
  modules/aws_vpc/outputs.tf
  modules/aws_vpc/variables.tf
  modules/kubeconfig/main.tf
  modules/kubeconfig/templates/kubeconfig-provider.tmpl
  modules/kubeconfig/variables.tf
  variables.tf
Labels: documentation, enhancement

#62 Changed kubeconfig flag default value
  variables.tf
Labels: enhancement

#65 Updated diagram
  docs/images/viya4-iac-aws-diag.png
Labels: documentation
