Repository sassoftware/viya4-iac-aws, pull requests merged in 2021-07, with the labels that each got.

#81 (#80) use unique postgres final snapshot name
  main.tf
Labels: enhancement

#78 Added in logic to fix auto scaling node startup
  examples/sample-input-minimal.tfvars
  main.tf
  variables.tf
Labels: bug

#79 (#75) use byo vpc cidr for nfs export and private cluster range
  main.tf
  modules/aws_vpc/outputs.tf
Labels: bug

#84 Private cluster
  .gitignore
  docs/CONFIG-VARS.md
  examples/sample-input-byo.tfvars
  examples/sample-input-custom-data.tfvars
  examples/sample-input-ha.tfvars
  examples/sample-input-minimal.tfvars
  examples/sample-input.tfvars
  files/custom-data/additional_userdata.sh
  files/policies/devops-iac-eks-policy.json
  locals.tf
  main.tf
  modules/aws_vpc/main.tf
  modules/aws_vpc/outputs.tf
  modules/aws_vpc/variables.tf
  outputs.tf
  variables.tf
Labels: documentation, enhancement
