Repository sassoftware/viya4-iac-aws, pull requests merged in 2022-09, with the labels that each got.

#156 feat: (IAC-544) AWS - support for k8s 1.23 and dropping 1.20
  Dockerfile
  README.md
  docs/CONFIG-VARS.md
  examples/sample-input-byo.tfvars
  examples/sample-input-connect.tfvars
  examples/sample-input-custom-data.tfvars
  examples/sample-input-gpu.tfvars
  examples/sample-input-ha.tfvars
  examples/sample-input-minimal.tfvars
  examples/sample-input.tfvars
  variables.tf
Labels: documentation, enhancement

#158 fix: (IAC-700) change to pre_bootstrap_user_data for node pools
  locals.tf
Labels: bug

#160 feat: (IAC-704) Update default postgresSQL server_version to v13
  docs/CONFIG-VARS.md
  variables.tf
Labels: documentation, enhancement

#159 feat: (IAC-667) Add ebs_csi module for AWS policy and role objects to support the aws ebs csi driver in EKS 1.23
  main.tf
  modules/aws_ebs_csi/main.tf
  modules/aws_ebs_csi/outputs.tf
  modules/aws_ebs_csi/variables.tf
  outputs.tf
  versions.tf
Labels: enhancement

#162 docs: (IAC-704) Update server_version notes
  docs/CONFIG-VARS.md
Labels: documentation

#152 fix: (IAC-632) tfvars PREFIX not applied to host nodes for k8s/Viya
  locals.tf
Labels: bug
