Repository sassoftware/viya4-iac-aws, pull requests merged in 2022-10, with the labels that each got.

#163 5.2.0 - October 3, 2022
  Dockerfile
  README.md
  docs/CONFIG-VARS.md
  examples/sample-input-byo.tfvars
  examples/sample-input-connect.tfvars
  examples/sample-input-custom-data.tfvars
  examples/sample-input-gpu.tfvars
  examples/sample-input-ha.tfvars
  examples/sample-input-minimal.tfvars
  examples/sample-input.tfvars
  locals.tf
  main.tf
  modules/aws_ebs_csi/main.tf
  modules/aws_ebs_csi/outputs.tf
  modules/aws_ebs_csi/variables.tf
  outputs.tf
  variables.tf
  versions.tf
Labels: bug, documentation, enhancement

#164 feat: (IAC-731) Back down the Postgres version to v12
  docs/CONFIG-VARS.md
  variables.tf
Labels: enhancement

#165 feat: (IAC-735): support longer length for PREFIX
  locals.tf
Labels: enhancement

#168 5.3.0 - October 20, 2022
  docs/CONFIG-VARS.md
  locals.tf
  variables.tf
Labels: documentation, enhancement
