Repository sassoftware/viya4-iac-aws, pull requests merged in 2023-11, with the labels that each got.

#238 feat!: (IAC-619) Support VPCs with ONLY private subnets, NAT gateway is not required
  docs/CONFIG-VARS.md
  docs/user/BYOnetwork.md
  locals.tf
  main.tf
  modules/aws_vpc/main.tf
  modules/aws_vpc/outputs.tf
  modules/aws_vpc/variables.tf
  modules/kubeconfig/main.tf
  modules/kubeconfig/variables.tf
  outputs.tf
  security.tf
  variables.tf
Labels: documentation, enhancement

#239 feat!: (IAC-1174) EKS Node Pool Subnets to use Single AZ by Default
  docs/CONFIG-VARS.md
  main.tf
  modules/aws_vpc/main.tf
  modules/aws_vpc/outputs.tf
  modules/aws_vpc/variables.tf
  variables.tf
Labels: enhancement

#240 feat: (IAC-367) Allow Ability To Specify Which Availability Zones the Subnets Get Created In
  docs/CONFIG-VARS.md
  locals.tf
  main.tf
  modules/aws_vpc/main.tf
  modules/aws_vpc/variables.tf
  outputs.tf
  variables.tf
Labels: enhancement

#244 chore: (IAC-1226) Ignore terraform_deprecated_lookup rule, resolve in future release.
  linting-configs/.tflint.hcl
Labels: enhancement

#241 docs: (IAC-1218) Update Subnet Example to be Single AZ Only
  docs/CONFIG-VARS.md
Labels: documentation

#242 docs: (IAC-352) Subnet requirements need more clarity in doc
  docs/CONFIG-VARS.md
Labels: documentation

#245 fix: (IAC-1229) coalescelist failed: no non-null arguments error with byo_network_scenario=3
  docs/CONFIG-VARS.md
  docs/user/BYOnetwork.md
  locals.tf
  main.tf
  security.tf
  variables.tf
Labels: bug

#246 feat!: (IAC-1190) Update Providers, Modules, & Binaries
  Dockerfile
  README.md
  docs/user/TerraformAWSAuthentication.md
  docs/user/TerraformUsage.md
  files/custom-data/additional_userdata.sh
  locals.tf
  main.tf
  modules/aws_autoscaling/main.tf
  modules/aws_ebs_csi/main.tf
  modules/aws_vm/main.tf
  modules/kubeconfig/main.tf
  outputs.tf
  security.tf
  versions.tf
Labels: documentation, enhancement

#247 chore: (IAC-1227) enable terraform_deprecated_lookup
  linting-configs/.tflint.hcl
  main.tf
Labels: enhancement

#248 fix: (IAC-1240) cluster_api_mode=public requires ingress rules for API server's private IP address
  locals.tf
Labels: bug
