Repository sassoftware/viya4-iac-aws, pull requests merged in 2023-05, with the labels that each got.

#205 feat: (IAC-980) add K8s 1.26 support, set kubectl default to 1.25
  Dockerfile
  README.md
  docs/CONFIG-VARS.md
  examples/sample-input-byo.tfvars
  examples/sample-input-connect.tfvars
  examples/sample-input-custom-data.tfvars
  examples/sample-input-gpu.tfvars
  examples/sample-input-ha.tfvars
  examples/sample-input-minimal.tfvars
  examples/sample-input-singlestore.tfvars
  examples/sample-input.tfvars
  variables.tf
Labels: documentation, enhancement

#206 feat!: (IAC-969) Update Terraform version to latest - 1.4.5
  Dockerfile
  README.md
  container-structure-test.yaml
  versions.tf
Labels: documentation, enhancement

#195 doc: (IAC-948) fixed viya4-iac-aws doc points to AWS EKS doc
  README.md
Labels: bug, documentation

#193 feat: (IAC-168) added efs_throughput_mode & rate variables needed in iac-aws terraform.tfvars
  docs/CONFIG-VARS.md
  variables.tf
  vms.tf
Labels: enhancement

#176 feat: (IAC-811): Added GitHub Actions (hadolint, shellcheck, tflint) to the AWS repo.
  .github/workflows/linter-analysis.yaml
  docker-entrypoint.sh
  linting-configs/.hadolint.yaml
  linting-configs/.shellcheckrc
  linting-configs/.tflint.hcl
  locals.tf
  modules/aws_vm/main.tf
  modules/aws_vm/outputs.tf
  modules/aws_vpc/main.tf
  modules/aws_vpc/outputs.tf
  modules/kubeconfig/main.tf
  security.tf
  vms.tf
Labels: enhancement
