Repository sassoftware/viya4-iac-aws, pull requests merged in 2024-07, with the labels that each got.

#293 feat: (IAC-1472) AWS - Security scan 2024.06
  Dockerfile
  container-structure-test.yaml
Labels: enhancement

#294 feat: (#PSKD-410) - Enable NIST support flag
  linting-configs/.tflint.hcl
  modules/aws_vm/main.tf
  modules/aws_vm/variables.tf
  outputs.tf
  variables.tf
Labels: enhancement

#295 fix: (PSKD-494) AWS - private endpoint type for S3 should be of type Interface
  variables.tf
Labels: bug

#296 8.4.0 - July 22, 2024
  Dockerfile
  container-structure-test.yaml
  variables.tf
Labels: bug, enhancement

#297 feat: (PSKD-517) Add Support for K8s 1.30
  Dockerfile
  README.md
  docs/CONFIG-VARS.md
  examples/sample-input-byo.tfvars
  examples/sample-input-connect.tfvars
  examples/sample-input-custom-data.tfvars
  examples/sample-input-gpu.tfvars
  examples/sample-input-ha.tfvars
  examples/sample-input-minimal.tfvars
  examples/sample-input-singlestore.tfvars
  examples/sample-input.tfvars
  variables.tf
Labels: documentation, enhancement
