Repository sassoftware/viya4-iac-aws, pull requests merged in 2024-04, with the labels that each got.

#279 feat: (IAC-1376) Add Support for K8s 1.29
  Dockerfile
  README.md
  docs/CONFIG-VARS.md
  examples/sample-input-byo.tfvars
  examples/sample-input-connect.tfvars
  examples/sample-input-custom-data.tfvars
  examples/sample-input-gpu.tfvars
  examples/sample-input-ha.tfvars
  examples/sample-input-minimal.tfvars
  examples/sample-input-singlestore.tfvars
  examples/sample-input.tfvars
  variables.tf
Labels: documentation, enhancement

#281 docs: (IAC-1411) Updated copyright range to 2024
  container-structure-test.yaml
  docker-entrypoint.sh
  files/tools/iac_git_info.sh
  files/tools/iac_tooling_version.sh
  locals.tf
  main.tf
  modules/aws_autoscaling/main.tf
  modules/aws_autoscaling/outputs.tf
  modules/aws_autoscaling/variables.tf
  modules/aws_ebs_csi/main.tf
  modules/aws_ebs_csi/outputs.tf
  modules/aws_ebs_csi/variables.tf
  modules/aws_fsx_ontap/main.tf
  modules/aws_fsx_ontap/outputs.tf
  modules/aws_fsx_ontap/variables.tf
  modules/aws_vm/main.tf
  modules/aws_vm/outputs.tf
  modules/aws_vm/variables.tf
  modules/aws_vpc/main.tf
  modules/aws_vpc/outputs.tf
  modules/aws_vpc/variables.tf
  modules/kubeconfig/main.tf
  modules/kubeconfig/outputs.tf
  modules/kubeconfig/variables.tf
  outputs.tf
  security.tf
  variables.tf
  versions.tf
  vms.tf
Labels: documentation

#282 fix: (IAC-1380) AWS Autoscaling Launch Template Tags Incorrect
  locals.tf
Labels: bug
