Repository sassoftware/viya4-iac-aws, pull requests merged in 2025-03, with the labels that each got.

#328 chore: AWS - Security scan 2025.03 (PSKD-1402)
  .github/workflows/linter-analysis.yaml
  Dockerfile
  README.md
  container-structure-test.yaml
  versions.tf
Labels: documentation

#330 chore: Update AWS instance types to align with WW Sizing recommendations (PSKD-650)
  docs/CONFIG-VARS.md
  examples/sample-input-byo.tfvars
  examples/sample-input-connect.tfvars
  examples/sample-input-custom-data.tfvars
  examples/sample-input-gpu.tfvars
  examples/sample-input-ha.tfvars
  examples/sample-input-minimal.tfvars
  examples/sample-input-singlestore.tfvars
  examples/sample-input.tfvars
  modules/aws_vm/variables.tf
  variables.tf
Labels: documentation, enhancement

#332 docs: Add additional security_group_ids to sample-input-byo.tfvars (PSKD-1292)
  examples/sample-input-byo.tfvars
  test/default_unit_test.go
Labels: documentation

#333 docs: Correct parameter value syntax for external postgres servers (PSKD-1439)
  docs/CONFIG-VARS.md
Labels: documentation

#339 ci: (PSKD-1515) add release workflows
  .github/release-drafter.yml
  .github/workflows/conventional-commits.yml
  .github/workflows/draft-release.yml
  .github/workflows/semvar.yml
Labels: CI/CD
